# Docker Compose
version: '3'
services:

        postgres:
                build:
                        context: docker/postgresql/
                environment:
                        - POSTGRES_USER=$DB_USERNAME
                        - POSTGRES_PASSWORD=$DB_PASSWORD
                ports:
                        - 5433:5432
                restart: always
                volumes:
                        - "persist_volume:/var/lib/postgresql/data"

        app:
                build:
                        context: .
                        dockerfile: docker/flask/Dockerfile
                entrypoint: ./build.sh
                env_file: .env
                ports:
                        - 5000:5000
                depends_on:
                        - postgres
                restart: always

volumes:
        persist_volume:
